# subtitile
demuxer-mkv-subtitle-preroll=yes
demuxer-mkv-subtitle-preroll-secs=2
sub-filter-sdh=yes
embeddedfonts=yes

sub-font='Noto Sans SemiBold'
sub-font='Noto Sans SC SemiBold'
sub-color='#FFFFFF'
sub-border-color='#000000'
sub-border-size=0.3
sub-shadow-color='#000000'
sub-shadow-offset=1
sub-font-size=42
sub-pos=100
sub-use-margins
sub-ass-force-margins

sub-auto=fuzzy
blend-subtitles=no

# general
msg-color
term-osd-bar
pause
keep-open=yes
cursor-autohide-fs-only
hls-bitrate=max 
fullscreen=yes
screenshot-format=png
screenshot-dir="~/Pictures/Screenshots"

profile=high-quality
deband=yes
icc-profile-auto=yes
video-sync=display-resample
#interpolation=yes
tscale=oversample
hwdec=auto-safe
save-position-on-quit=yes
watch-later-options=start,vid,aid,sid

# languages
slang=en,eng,enm,de,deu,ger
